# Generated by Django 5.1.7 on 2026-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.AddField(
            model_name='car',
            name='down_payment',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
    ]
