# Generated by Django 6.0.5 on 2026-05-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_car_title_car_down_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='financing',
            field=models.PositiveIntegerField(blank=True, default=500, null=True),
        ),
    ]
