# Generated by Django 6.0.5 on 2026-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_financing'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
