# Generated by Django 6.0.5 on 2026-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_vin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-created_at'], name='car_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model'], name='car_make_model_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['vin_number'], name='car_vin_number_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['condition'], name='car_condition_idx'),
        ),
    ]
